- name: Run script to upgrade cluster
  include_tasks: upgrade.yml
  when: acc_provision_input['operator_managed_config'] is defined and acc_provision_input['operator_managed_config']['enable_updates'] is defined and acc_provision_input['operator_managed_config']['enable_updates'] == true
