- name: Prinmt name ----------------------------
  vars:
    msg: "{{ hostvars['localhost']['_aci_ctrl_accprovisioninput']['metadata']['name'] | to_nice_json }}"
  set_fact:
    cr_namee: "{{ msg.split('\n') }}"

- name: Prinmt name ----------------------------
  vars:
    msg: "{{ hostvars['localhost']['_aci_ctrl_accprovisioninput']['metadata']['resourceVersion'] | to_nice_json }}"
  set_fact:
    cr_versionn: "{{ msg.split('\n') }}"

- name: strip quotes
  set_fact:
    cr_name: "{{ cr_namee[0][1:-1] }}"
    cr_version: "{{ cr_versionn[0][1:-1] }}"

- name: print the CR name +++++++++++++
  debug:
    msg: "{{ cr_name }}"

- name: print the CR resourceVersion
  debug:
    msg: "{{ cr_version }}"

- name: Create temporary directory for acc-provision run
  file:
    path: "{{ acc_provision_dir_path }}"
    state: directory
    mode: '0777'

- name: check if file exists
  stat:
    path: "/tmp/acc_provision/version"
  register: file_present

- name: Get current resourceVersion set
  set_fact:
    current_version: "{{ lookup('file', '/tmp/acc_provision/version') }}"
  when: file_present.stat.exists

- name: create file
  file:
    path: /tmp/acc_provision/version
    state: touch
  when: not file_present.stat.exists

- name: default version
  set_fact:
    current_version: ""
  when: not file_present.stat.exists

- name: print the old CR resourceVersion
  debug:
    msg: "{{ current_version }}"

- name: cache the new resourceVersion
  copy: content="{{ cr_version }}" dest='/tmp/acc_provision/version'
  when: cr_name == "accprovisioninput"

- include_tasks: process.yaml
  when: cr_name == "accprovisioninput" and cr_version != current_version
