---
- name: Get acc-provision configmap
  k8s_info:
    api_version: v1
    kind: ConfigMap
    name: acc-provision-config
    namespace: "{{ lookup('env', 'WATCH_NAMESPACE') }}"
  register: cmap_data

- name: Set fact
  set_fact:
    cmap_content: "{{ cmap_data['resources'][0]}}"

- name: Write cmap YAML
  copy:
    dest: "{{ acc_provision_dir_path }}/cmap.yaml"
    content: "{{ cmap_content }}"

- name: Set input YAML
  set_fact:
    cmap_input: "{{ cmap_data['resources'][0]['data']['spec'] }}"

- name: Get CRD definition for accprovisioninput
  community.kubernetes.k8s_info:
    api_version: v1
    kind: CustomResourceDefinition
    name: accprovisioninputs.aci.ctrl
  register: raw_crd

# This task picks the first schema defined under the CRD
- name: Get crd definition from raw k8s resource
  set_fact:
    crd_definition: "{{ raw_crd['resources'][0]['spec']['versions'][0]['schema']['openAPIV3Schema']['properties']['spec']['properties']['acc_provision_input']['properties'] }}"
