---
- name: Create directory for acc-provision run
  file:
    path: "{{ acc_provision_dir_path }}"
    state: directory
    mode: '0755'

- name: Get acc-provision configmap
  k8s_info:
    api_version: v1
    kind: ConfigMap
    name: acc-provision-config
    namespace: "{{ lookup('env', 'WATCH_NAMESPACE') }}"
  register: cmap_data

- name: Collecting config-map content
  set_fact:
    cmap_content: "{{ cmap_data['resources'][0]}}"

- name: Write cmap YAML
  copy:
    dest: "{{ acc_provision_dir_path }}/cmap.yaml"
    content: "{{ cmap_content }}"

- name: Collecting config-map spec
  set_fact:
    cmap_input: "{{ cmap_data['resources'][0]['data']['spec'] }}"

- name: Get CRD definition for accprovisioninput
  community.kubernetes.k8s_info:
    api_version: v1
    kind: CustomResourceDefinition
    name: accprovisioninputs.aci.ctrl
  register: raw_crd

# This task picks the first schema defined under the CRD
- name: Get crd definition from raw k8s resource
  set_fact:
    crd_definition: "{{ raw_crd['resources'][0]['spec']['versions'][0]['schema']['openAPIV3Schema']['properties']['spec']['properties']['acc_provision_input']['properties'] }}"

- name: Compute acc-provision input file
  script: "scripts/compute_input_yaml.py"
  args:
    executable: /usr/bin/python3
  environment:
    CRDINPUT: "{{ acc_provision_input }}"
    CRD_DEFINITION: "{{ crd_definition }}"
    CONFIGMAP_INPUT_FILE: "{{ acc_provision_dir_path }}/cmap.yaml"
    ACCPROVDIR: "{{ acc_provision_dir_path }}"
    ACCPROVFILE: "{{ acc_provision_file_name }}"

- name: Get aci-containers-config-version from acc-provision-operator configmap
  set_fact:
    aci_containers_config_version: "{{ cmap_data['resources'][0]['metadata']['labels']['aci-containers-config-version'] }}"

- name: Generate new deployment yaml
  shell: "acc-provision -c {{ acc_provision_file_name }} -f {{ lookup('env', 'ACC_PROVISION_FLAVOR') }} -o {{ aci_cni_deployment_file }} --operator-mode True --version-token {{ aci_containers_config_version }}"
  args:
    chdir: "{{ acc_provision_dir_path }}"


- name: Convert aci_cni_deployment_file to base64
  shell: "cat {{ acc_provision_dir_path }}/{{ aci_cni_deployment_file }} | base64 -w 0"
  register: aci_operator_config


- name: Create the Aci Operator Conf File
  template:
    src: "aci-operator-conf.yaml"
    dest: "{{ acc_provision_dir_path }}/aci-operator-conf.yaml"

- wait_for:
    path: "{{ acc_provision_dir_path }}/aci-operator-conf.yaml"

- name: Run k8s command to create Aci Operator ConfigMap
  k8s:
    state: present
    src: "{{ acc_provision_dir_path }}/aci-operator-conf.yaml"
  register: config_result
  until: config_result is not failed
  retries: 5
  delay: 2


- name: Run k8s command to apply deployment file
  k8s:
    state: present
    src: "{{ acc_provision_dir_path }}/{{ aci_cni_deployment_file }}"
  register: k8s_result
  until: k8s_result is not failed
  retries: 5
  delay: 30



#
