# permissions for end users to edit accprovisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accprovision-editor-role
rules:
- apiGroups:
  - aci.accprov
  resources:
  - accprovisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aci.accprov
  resources:
  - accprovisions/status
  verbs:
  - get
