apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accprovisions.aci.accprov.com
spec:
  group: aci.accprov.com
  names:
    kind: AccProvision
    listKind: AccProvisionList
    plural: accprovisions
    singular: accprovision
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
