apiVersion: v1
kind: Namespace
metadata:
  name: aci-containers-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: net-operator-controller
  namespace: aci-containers-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    network-plugin: calico
  name: net-operator-controller
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - nodes
  - namespaces
  - configmaps
  - secrets
  - pods
  - services
  - serviceaccounts
  - serviceaccounts/token
  - endpoints
  - events
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - aci.ctrl
  resources:
  - accprovisioninputs
  - accprovisioninputs/status
  - accprovisioninputs/finalizers
  verbs:
  - '*'
- apiGroups:
  - scheduling.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: net-operator-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: net-operator-controller
subjects:
- kind: ServiceAccount
  name: net-operator-controller
  namespace: aci-containers-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accprovisioninputs.aci.ctrl
spec:
  group: aci.ctrl
  names:
    kind: AccProvisionInput
    listKind: AccProvisionInputList
    plural: accprovisioninputs
    singular: accprovisioninput
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: accprovisioninput defines the input configuration for ACI CNI
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: AccProvisionInputSpec defines the desired spec for accprovisioninput object
            properties:
              acc_provision_input:
                type: object
                properties:
                  operator_managed_config:
                    type: object
                    properties:
                      enable_updates:
                        type: boolean
                  aci_config:
                    type: object
                    properties:
                      sync_login:
                        type: object
                        properties:
                          certfile:
                            type: string
                          keyfile:
                            type: string
                      client_ssl:
                        type: boolean
                      system_id:
                        type: string
                      apic_hosts:
                        type: array
                        items:
                          type: string
                      vmm_domain:
                        type: object
                        properties:
                          encap_type:
                            type: string
                          mcast_range:
                            type: object
                            properties:
                              start:
                                type: string
                              end:
                                type: string
                      apic_login:
                        type: object
                        properties:
                          username:
                            type: string
                          password:
                            type: string
                      aep:
                        type: string
                      vrf:
                        type: object
                        properties:
                          name:
                            type: string
                          tenant:
                            type: string
                      l3out:
                        type: object
                        properties:
                          name:
                            type: string
                          external_networks:
                            type: array
                            items:
                              type: string
                  net_config:
                    type: object
                    properties:
                      interface_mtu:
                        type: integer
                      service_monitor_interval:
                        type: integer
                      pbr_tracking_non_snat:
                        type: boolean
                      pod_subnet_chunk_size:
                        type: integer
                      disable_wait_for_network:
                        type: boolean
                      duration_wait_for_network:
                        type: integer
                  registry:
                    type: object
                    properties:
                      image_prefix:
                        type: string
                      image_pull_secret:
                        type: string
                      aci_containers_operator_version:
                        type: string
                      aci_containers_controller_version:
                        type: string
                      aci_containers_host_version:
                        type: string
                      acc_provision_operator_version:
                        type: string
                      aci_cni_operator_version:
                        type: string
                      cnideploy_version:
                        type: string
                      opflex_agent_version:
                        type: string
                      openvswitch_version:
                        type: string
                      gbp_version:
                        type: string
                      network_operator_version:
                        type: string
                  logging:
                    type: object
                    properties:
                      controller_log_level:
                        type: string
                      hostagent_log_level:
                        type: string
                      opflexagent_log_level:
                        type: string
                  istio_config:
                    type: object
                    properties:
                      install_istio:
                        type: boolean
                      install_profile:
                        type: string
                  multus:
                    type: object
                    properties:
                      disable:
                        type: boolean
                  drop_log_config:
                    type: object
                    properties:
                      enable:
                        type: boolean
                  nodepodif_config:
                    type: object
                    properties:
                      enable:
                        type: boolean
                  sriov_config:
                    type: object
                    properties:
                      enable:
                        type: boolean
                  kube_config:
                    type: object
                    properties:
                      ovs_memory_limit:
                        type: string
                      use_privileged_containers:
                        type: boolean
                      image_pull_policy:
                        type: string
                      reboot_opflex_with_ovs:
                        type: string
                      snat_operator:
                        type: object
                        properties:
                          port_range:
                            type: object
                            properties:
                              start:
                                type: integer
                              end:
                                type: integer
                              ports_per_node:
                                type: integer
                          contract_scope:
                            type: string
                          disable_periodic_snat_global_info_sync:
                            type: boolean
                  calico_config:
                    type: object
                    properties:
                      net_config:
                        type: object
                        properties:
                          block_size:
                            type: integer
                      bgp_config:
                        type: object
                        properties:
                          bgp_secret:
                            type: string
                      bgp_peer_config:
                        type: object
                        properties:
                          as_number:
                            type: integer
                          racks:
                            type: array
                            items:
                              type: array
                              items:
                               type: string
                  profile:
                    type: string
            type: object
          status:
            description: AccProvisionInputStatus defines the successful completion of AccProvisionInput
            properties:
              status:
                type: boolean
            type: object
        required:
        - spec
        type: object
---
apiVersion: v1
data:
  spec: "{\n    \"acc_provision_input\": {\n        \"operator_managed_config\": {\n\
    \            \"enable_updates\": false\n        },\n        \"aci_config\": {\n\
    \            \"system_id\": \"mykube\",\n            \"apic_hosts\": [\n     \
    \           \"10.1.1.101\"\n            ],\n            \"aep\": \"kube-cluster\"\
    ,\n            \"tenant\": {\n                \"name\": \"prj_5cc3c29ec36a49cf942ff84f9e8deb30\"\
    \n            },\n            \"vrf\": {\n                \"name\": \"mykube-vrf\"\
    ,\n                \"tenant\": \"common\"\n            },\n            \"l3out\"\
    : {\n                \"name\": \"mykube_l3out\",\n                \"external_networks\"\
    : [\n                    \"mykube_extepg\"\n                ]\n            }\n\
    \        },\n        \"registry\": {\n            \"aci_containers_controller_version\"\
    : \"kmr2-test\", \n            \"aci_containers_host_version\": \"kmr2-test\"\
    , \n            \"aci_containers_operator_version\": \"kmr2-test\", \n       \
    \     \"cnideploy_version\": \"kmr2-test\", \n            \"image_prefix\": \"\
    quay.io/noirolabs\", \n            \"network_operator_version\": \"test\", \n\
    \            \"openvswitch_version\": \"kmr2-test\", \n            \"opflex_agent_version\"\
    : \"kmr2-test\"\n        },\n        \"net_config\": {\n            \"infra_vlan\"\
    : 3801,\n            \"kubeapi_vlan\": 2032,\n\
    \            \"extern_dynamic\"\
    : \"dummy\",\n\
    \            \"node_subnet\": \"dummy\",\n            \"pod_subnet\": \"\
    dummy\"\n        }\n    }\n }"
kind: ConfigMap
metadata:
  name: acc-provision-config
  namespace: aci-containers-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-operator-controller
  namespace: aci-containers-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: net-operator-controller
      network-plugin: aci-containers
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
      labels:
        name: net-operator-controller
        network-plugin: aci-containers
      name: net-operator-controller
      namespace: aci-containers-system
    spec:
      containers:
      - env:
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ACC_PROVISION_FLAVOR
          value: cko-calico
        - name: ACC_PROVISION_INPUT_CR_NAME
          value: accprovisioninput
        image: quay.io/noirolabs/acc-provision-operator:abhishek
        imagePullPolicy: Always
        name: acc-provision-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: net-operator-controller
      serviceAccountName: net-operator-controller
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - configMap:
          items:
          - key: spec
            path: acc-provision-operator.conf
          name: acc-provision-config
        name: acc-provision-config
